# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Claw Hub'
        repository: 'dockerclaw/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags:
          $(tag)
- stage: Deployment
  displayName: 'deploying to Azure use terraform'
  dependsOn: Build
  jobs:
  - job:  Deployment
    displayName: 'deploying to Azure containers'
    pool:
      vmImage: 'ubuntu-latest'
    variables:
    - group: TerraformVars
    steps:
    - script: |
        set -e 
        terraform init -input=false
        terraform apply -input=false -auto-approve
